version: 1
policies:
  - id: medium-severity
    when:
      severity: medium
    result:
      exit-code: 1
      message: medium-severity message / Defect from a medium severity checker caused this failure.
  - id: high-severity
    when:
      severity: high
    result:
      exit-code: 1
      message: high-severity message / Defect from a high security checker caused this failure.
