name: Black Duck

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  blackduck:
    runs-on: ubuntu-latest

    env:
      PROJECT: chuckaude-hello-java
      BRANCH: ${GITHUB_REF##*/}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Environment
      run: |
        env | sort
    - name: Black Duck Scan with token
      uses: blackducksoftware/github-action@v2
      with:
        args: --blackduck.url=${{secrets.BD_HUB_URL}} --blackduck.api.token=${{secrets.BD_HUB_TOKEN}} --detect.tools=SIGNATURE_SCAN,DETECTOR
          --detect.project.name=$PROJECT --detect.project.version.name=$BRANCH
    - name: Black Duck Scan without token
      uses: blackducksoftware/github-action@v2
      with:
        args: --blackduck.url=${{secrets.BD_HUB_URL}} --detect.tools=SIGNATURE_SCAN,DETECTOR
          --detect.project.name=$PROJECT --detect.project.version.name=$BRANCH
