name: CoverityQualityGateDemo
on:
  push:
    branches: [ master ]
  workflow_dispatch:
 
jobs:
  Coverity:
 
    runs-on: self-hosted
 
    env:
      COV_URL: ${{ secrets.COV_URL }}
      COV_USER: ${{ secrets.COV_USER }}
      COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
      COVERITY_PROJECT: hello-java
      COVBIN: /opt/Coverity/cov-analysis/bin
      COVNODE: /opt/Coverity/cov-analysis/node/bin
      COVHOME: /opt/Coverity/cov-analysis
      BLDCMD: mvn -B clean compile
      CHECKERS: --webapp-security
 
    steps:
    - uses: AutoModality/action-clean@v1
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
 
    - name: Coverity Full Scan
      run: |
        export PATH=$PATH:$COVBIN
        set -x
        cov-build --dir idir --fs-capture-search $GITHUB_WORKSPACE $BLDCMD
        cov-analyze --dir idir --ticker-mode none --strip-path $GITHUB_WORKSPACE $CHECKERS
        cov-commit-defects --dir idir --ticker-mode none --url $COV_URL --stream $COVERITY_PROJECT-${GITHUB_REF##*/} --scm git \
          --description $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID --target $RUNNER_OS --version $GITHUB_SHA
        $COVBIN/cov-format-errors --dir idir --json-output-v8 cov-findings-v8.json
        $COVNODE/node $COVHOME/SARIF/cov-format-sarif-for-github.js --inputFile cov-findings-v8.json --outputFile cov-findings-sarif.json --repoName $GITHUB_REPOSITORY --checkoutPath $GITHUB_REPOSITORY `pwd` $GITHUB_SHA
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
         # Path to SARIF file relative to the root of the repository
         sarif_file: cov-findings-sarif.json          
    - name: Coverity Quality Gate
      run: |
        curl -fLsS --user $COV_USER:$COVERITY_PASSPHRASE $COV_URL/api/viewContents/issues/v1/Medium%20High%20Issues?projectId=$COVERITY_PROJECT > results.json
        if [ $(cat results.json | jq .viewContentsV1.totalRows) -ne 0 ]; then cat results.json | jq .viewContentsV1.rows; exit 1; fi
