name: SigmaQualityGateDemo
on:
  push:
    branches: [ master ]
  workflow_dispatch:
 
jobs:
  sigma_download_script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2      

      - name: Download SIGMA
        run: curl -k -L https://synopsyssf.sharefile.com/d-sf53ad0a8d3ce44c498b97f9d8d82029c      
 
      - name: SIGMA analysis
        run: ./sigma analyze --format github
